apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacman_git
  namespace: pacman_git
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pacman_git
rules:
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pacman_git
  namespace: pacman_git
subjects:
- kind: ServiceAccount
  name: pacman_git
  namespace: pacman_git2
roleRef:
  kind: ClusterRole
  name: pacman_git
  apiGroup: rbac.authorization.k8s.io